### ISSUE TITLE
Dropdown closes after search then select item

### ISSUE THREAD

**Issue by programmercpp** [NileshPatel17/ng-multiselect-dropdown#338] opened 2021-12-23 14:15 UTC
I search something into search text.
From searched option, I select one of the option from dropdown.
Again I click on search input to change the searching text.. At that time dropdown is getting close unnecessarily.

**Comment by rooby** [comment] 2022-01-25 06:43
This is a duplicate of #295

**Comment by NileshPatel17** [comment] 2022-01-25 06:52
@rooby thanks for pointing it out. closing it..

**Closed by NileshPatel17** 2022-01-25 06:52 UTC
